
    #!/bin/sh

    ## name of Job
    #PBS -N Annotation_

    ## Redirect output stream to this file.
    #PBS -o /media/inter/mkapun/projects/WolbachiaEvolHist_2023/results/mapping_mito/CK2_log.txt

    ## Stream Standard Output AND Standard Error to outputfile (see above)
    #PBS -j oe

    ## Select a maximum walltime of 2h
    #PBS -l walltime=100:00:00

    ## Select a maximum of 20 cores and 500gb of RAM
    #PBS -l select=1:ncpus=20:mem=100gb

    ### dependenceies

    module load NGSmapper/bwa-0.7.13
    module load NGSmapper/minimap2-2.17
    module load Tools/samtools-1.12

    bwa mem         -t 20         /media/inter/mkapun/projects/WolbachiaEvolHist_2023/data/db/NC_024511.2_start.fasta         /media/inter/mkapun/projects/WolbachiaEvolHist_2023/results/kraken_mito/CK2_1.fq.gz         /media/inter/mkapun/projects/WolbachiaEvolHist_2023/results/kraken_mito/CK2_2.fq.gz |
        samtools view -F 4 -bh | samtools sort         >/media/inter/mkapun/projects/WolbachiaEvolHist_2023/results/mapping_mito/CK2.bam

    # echo /media/inter/mkapun/projects/WolbachiaEvolHist_2023/results/mapping_mito/CK2.bam     # >>  /media/inter/mkapun/projects/WolbachiaEvolHist_2023/results/MergedData/bamlist_Mito.txt

    
